---
title: "PF_MATLABとKalmanの比較"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

MATLABのパーティクルフィルタがカルマンフィルタと同じ結果になっているか(コードにミスがないか確認)
## フィルタリング

```{r }
setwd("/home/naoya/PF_MATLAB")
library(dlm)
library(ggplot2)
library(reshape2)
library(dplyr)
theme_set(theme_bw())
beta <- 0.75
q_qnorm <- -2.053749
rho <- 0.08
X_0 <- -2.5
answer_X <- read.csv("data/matlab_X.csv",header = F)
data <- read.csv("data/matlab_DR.csv",header = F)
colnames(answer_X) <- c("answer")
pf <- read.csv("data/matlab_pf.csv",header = F)
colnames(pf) <- c("Particle_filter")
sm <- read.csv("data/matlab_sm.csv",header = F)
colnames(sm) <- c("Particle_smoother")
```

## Kalman

```{r}
mod1 <- dlm(m0=beta*(-2.5), C0=1 - beta, FF=-sqrt(beta*rho)/sqrt(1-rho),
             V=rho*(1-beta)/(1-rho), GG=sqrt(beta), W=1-beta )
fit_mod1 <- dlmFilter(data[-1,]-q_qnorm/sqrt(1-rho), mod1)
str(fit_mod1, 1)
```

```{r}
df_res1 <- data.frame(time=c(1:99), answer_X=answer_X[-100,], 
#                      predict_X_Kalman=fit_mod1$a,
                      filter_X_Kalman=fit_mod1$m[-1],
                      filter_X_particle=pf[-100,])
ggplot(df_res1 %>% melt("time") , aes(x=time,y=value,colour=variable))+
  geom_line() + ggtitle("X 状態変数")
```

## 平滑化

```{r}
fit_mod2 <- dlmSmooth(data[-1,]-q_qnorm/sqrt(1-rho),mod1)
smoother_X_Kalman <- fit_mod2$s[-1]
```

```{r}
df_res2 <- data.frame(time=c(1:99), answer_X=answer_X[-100,], 
#                      predict_X_Kalman=fit_mod1$a,
                      sm_X_Kalman=smoother_X_Kalman,
                      sm_X_particle=sm[-100,])
ggplot(df_res2 %>% melt("time") , aes(x=time,y=value,colour=variable))+
  geom_line() + ggtitle("X 状態変数")
```
